/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  jsonb,
  timestamp,
  numeric,
  boolean,
  integer,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_category_groups_sort_products = pgEnum('enum_category_groups_sort_products', [
  '-sold',
  '-createdAt',
  '-updatedAt',
])
export const enum_users_roles = pgEnum('enum_users_roles', ['admin', 'staff', 'user'])
export const enum_products_status = pgEnum('enum_products_status', ['PRIVATE', 'PUBLIC', 'STOPPED'])
export const enum_product_variants_status = pgEnum('enum_product_variants_status', [
  'ORDER',
  'AVAILABLE',
  'STOPPED',
  'PRIVATE',
])
export const enum_product_variants_auto_process = pgEnum('enum_product_variants_auto_process', [
  'key',
  'direct',
])
export const enum_orders_status = pgEnum('enum_orders_status', [
  'IN_QUEUE',
  'IN_PROCESS',
  'USER_UPDATE',
  'COMPLETED',
  'REFUND',
])
export const enum_recharges_status = pgEnum('enum_recharges_status', [
  'PENDING',
  'CANCEL',
  'SUCCESS',
  'REFUND',
])
export const enum_recharges_gateway = pgEnum('enum_recharges_gateway', ['PAYOS', 'DOITHE'])
export const enum_suppliers_status = pgEnum('enum_suppliers_status', ['ACTIVE', 'INACTIVE'])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum__posts_v_version_status = pgEnum('enum__posts_v_version_status', [
  'draft',
  'published',
])
export const enum_vouchers_discount_type = pgEnum('enum_vouchers_discount_type', [
  'percentage',
  'fixed',
])
export const enum_vouchers_commission_type = pgEnum('enum_vouchers_commission_type', [
  'percentage',
  'fixed',
])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'schedulePublish',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'schedulePublish',
])

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    caption: jsonb('caption'),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_og_url: varchar('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width', { mode: 'number' }),
    sizes_og_height: numeric('sizes_og_height', { mode: 'number' }),
    sizes_og_mimeType: varchar('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize', { mode: 'number' }),
    sizes_og_filename: varchar('sizes_og_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_og_sizes_og_filename_idx').on(columns.sizes_og_filename),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    icon: varchar('icon'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const category_groups = pgTable(
  'category_groups',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    icon: varchar('icon').notNull().default('box'),
    showOnHomepage: boolean('show_on_homepage').default(false),
    homepageSubtitle: varchar('homepage_subtitle'),
    sortOrder: numeric('sort_order', { mode: 'number' }).default(0),
    sortProducts: enum_category_groups_sort_products('sort_products').default('-sold'),
    homepageLimit: numeric('homepage_limit', { mode: 'number' }).default(12),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('category_groups_slug_idx').on(columns.slug),
    index('category_groups_updated_at_idx').on(columns.updatedAt),
    index('category_groups_created_at_idx').on(columns.createdAt),
  ],
)

export const category_groups_rels = pgTable(
  'category_groups_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('category_groups_rels_order_idx').on(columns.order),
    index('category_groups_rels_parent_idx').on(columns.parent),
    index('category_groups_rels_path_idx').on(columns.path),
    uniqueIndex('category_groups_rels_categories_id_idx').on(columns.categoriesID, columns.path),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [category_groups.id],
      name: 'category_groups_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'category_groups_rels_categories_fk',
    }).onDelete('cascade'),
  ],
)

export const accounts = pgTable(
  'accounts',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    picture: varchar('picture'),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    issuerName: varchar('issuer_name').notNull(),
    scope: varchar('scope'),
    sub: varchar('sub').notNull(),
    passkey_credentialId: varchar('passkey_credential_id'),
    passkey_publicKey: jsonb('passkey_public_key'),
    passkey_counter: numeric('passkey_counter', { mode: 'number' }),
    passkey_transports: jsonb('passkey_transports'),
    passkey_deviceType: varchar('passkey_device_type'),
    passkey_backedUp: boolean('passkey_backed_up').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('accounts_user_idx').on(columns.user),
    index('accounts_updated_at_idx').on(columns.updatedAt),
    index('accounts_created_at_idx').on(columns.createdAt),
  ],
)

export const users_roles = pgTable(
  'users_roles',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_users_roles('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('users_roles_order_idx').on(columns.order),
    index('users_roles_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_roles_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    balance: numeric('balance', { mode: 'number' }).default(0),
    chatwootHash: varchar('chatwoot_hash'),
    novuHash: varchar('novu_hash'),
    note: varchar('note'),
    ip: varchar('ip'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const stocks = pgTable(
  'stocks',
  {
    id: serial('id').primaryKey(),
    order: integer('order_id').references(() => orders.id, {
      onDelete: 'set null',
    }),
    productVariant: integer('product_variant_id')
      .notNull()
      .references(() => product_variants.id, {
        onDelete: 'set null',
      }),
    data: jsonb('data').notNull(),
    expiredAt: timestamp('expired_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('stocks_order_idx').on(columns.order),
    index('stocks_product_variant_idx').on(columns.productVariant),
    index('stocks_updated_at_idx').on(columns.updatedAt),
    index('stocks_created_at_idx').on(columns.createdAt),
  ],
)

export const transactions = pgTable(
  'transactions',
  {
    id: serial('id').primaryKey(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    balance: numeric('balance', { mode: 'number' }).notNull(),
    description: varchar('description').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('transactions_user_idx').on(columns.user),
    index('transactions_updated_at_idx').on(columns.updatedAt),
    index('transactions_created_at_idx').on(columns.createdAt),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    status: enum_products_status('status').notNull(),
    sold: numeric('sold', { mode: 'number' }).notNull().default(0),
    minPrice: numeric('min_price', { mode: 'number' }).notNull().default(0),
    maxPrice: numeric('max_price', { mode: 'number' }).notNull().default(0),
    maxDiscount: numeric('max_discount', { mode: 'number' }).notNull().default(0),
    note: varchar('note'),
    description: jsonb('description'),
    featured: boolean('featured').default(false),
    slug: varchar('slug'),
    slugLock: boolean('slug_lock').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('products_image_idx').on(columns.image),
    index('products_slug_idx').on(columns.slug),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
  ],
)

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'product-variantsID': integer('product_variants_id'),
    productsID: integer('products_id'),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('products_rels_order_idx').on(columns.order),
    index('products_rels_parent_idx').on(columns.parent),
    index('products_rels_path_idx').on(columns.path),
    uniqueIndex('products_rels_product_variants_id_idx').on(
      columns['product-variantsID'],
      columns.path,
    ),
    index('products_rels_products_id_idx').on(columns.productsID),
    index('products_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['product-variantsID']],
      foreignColumns: [product_variants.id],
      name: 'products_rels_product_variants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'products_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'products_rels_categories_fk',
    }).onDelete('cascade'),
  ],
)

export const product_variants = pgTable(
  'product_variants',
  {
    id: serial('id').primaryKey(),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    sold: numeric('sold', { mode: 'number' }).notNull().default(0),
    important: jsonb('important'),
    name: varchar('name').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_product_variants_status('status').notNull(),
    form: integer('form_id').references(() => forms.id, {
      onDelete: 'set null',
    }),
    originalPrice: numeric('original_price', { mode: 'number' }).notNull(),
    price: numeric('price', { mode: 'number' }).notNull(),
    min: numeric('min', { mode: 'number' }).notNull().default(1),
    max: numeric('max', { mode: 'number' }).notNull().default(1),
    note: varchar('note'),
    description: jsonb('description'),
    fixedStock: jsonb('fixed_stock'),
    defaultSupplier: integer('default_supplier_id').references(() => suppliers.id, {
      onDelete: 'set null',
    }),
    autoProcess: enum_product_variants_auto_process('auto_process'),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('product_variants_product_idx').on(columns.product),
    index('product_variants_image_idx').on(columns.image),
    index('product_variants_form_idx').on(columns.form),
    index('product_variants_default_supplier_idx').on(columns.defaultSupplier),
    index('product_variants_updated_at_idx').on(columns.updatedAt),
    index('product_variants_created_at_idx').on(columns.createdAt),
  ],
)

export const product_variant_supplies = pgTable(
  'product_variant_supplies',
  {
    id: serial('id').primaryKey(),
    productVariant: integer('product_variant_id')
      .notNull()
      .references(() => product_variants.id, {
        onDelete: 'set null',
      }),
    supplier: integer('supplier_id')
      .notNull()
      .references(() => suppliers.id, {
        onDelete: 'set null',
      }),
    cost: numeric('cost', { mode: 'number' }).notNull().default(0),
    prepaid: boolean('prepaid').notNull().default(false),
    purchase: numeric('purchase', { mode: 'number' }).notNull().default(0),
    note: varchar('note'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('product_variant_supplies_product_variant_idx').on(columns.productVariant),
    index('product_variant_supplies_supplier_idx').on(columns.supplier),
    index('product_variant_supplies_updated_at_idx').on(columns.updatedAt),
    index('product_variant_supplies_created_at_idx').on(columns.createdAt),
    uniqueIndex('productVariant_supplier_idx').on(columns.productVariant, columns.supplier),
  ],
)

export const orders = pgTable(
  'orders',
  {
    id: serial('id').primaryKey(),
    note: jsonb('note'),
    message: jsonb('message'),
    deliveryContent: jsonb('delivery_content'),
    status: enum_orders_status('status').notNull().default('IN_QUEUE'),
    orderedBy: integer('ordered_by_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    productVariant: integer('product_variant_id')
      .notNull()
      .references(() => product_variants.id, {
        onDelete: 'set null',
      }),
    formSubmission: integer('form_submission_id').references(() => form_submissions.id, {
      onDelete: 'set null',
    }),
    subTotal: numeric('sub_total', { mode: 'number' }).notNull(),
    totalDiscount: numeric('total_discount', { mode: 'number' }).notNull(),
    totalPrice: numeric('total_price', { mode: 'number' }).notNull(),
    quantity: numeric('quantity', { mode: 'number' }).notNull(),
    supplier: integer('supplier_id').references(() => suppliers.id, {
      onDelete: 'set null',
    }),
    supplierPaid: boolean('supplier_paid'),
    cost: numeric('cost', { mode: 'number' }),
    revenue: numeric('revenue', { mode: 'number' }),
    voucher: integer('voucher_id').references(() => vouchers.id, {
      onDelete: 'set null',
    }),
    voucherDiscount: numeric('voucher_discount', { mode: 'number' }),
    affiliateUser: integer('affiliate_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    affiliateCommission: numeric('affiliate_commission', { mode: 'number' }),
    affiliatePaid: boolean('affiliate_paid').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('orders_ordered_by_idx').on(columns.orderedBy),
    index('orders_product_variant_idx').on(columns.productVariant),
    index('orders_form_submission_idx').on(columns.formSubmission),
    index('orders_supplier_idx').on(columns.supplier),
    index('orders_voucher_idx').on(columns.voucher),
    index('orders_affiliate_user_idx').on(columns.affiliateUser),
    index('orders_updated_at_idx').on(columns.updatedAt),
    index('orders_created_at_idx').on(columns.createdAt),
  ],
)

export const orders_rels = pgTable(
  'orders_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('orders_rels_order_idx').on(columns.order),
    index('orders_rels_parent_idx').on(columns.parent),
    index('orders_rels_path_idx').on(columns.path),
    index('orders_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [orders.id],
      name: 'orders_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'orders_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const recharges = pgTable(
  'recharges',
  {
    id: serial('id').primaryKey(),
    status: enum_recharges_status('status').notNull().default('PENDING'),
    orderCode: varchar('order_code').notNull(),
    gateway: enum_recharges_gateway('gateway').notNull().default('PAYOS'),
    data: jsonb('data'),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('recharges_order_code_idx').on(columns.orderCode),
    index('recharges_user_idx').on(columns.user),
    index('recharges_updated_at_idx').on(columns.updatedAt),
    index('recharges_created_at_idx').on(columns.createdAt),
    uniqueIndex('orderCode_gateway_idx').on(columns.orderCode, columns.gateway),
  ],
)

export const forms_blocks_checkbox = pgTable(
  'forms_blocks_checkbox',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    required: boolean('required'),
    defaultValue: boolean('default_value'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_checkbox_order_idx').on(columns._order),
    index('forms_blocks_checkbox_parent_id_idx').on(columns._parentID),
    index('forms_blocks_checkbox_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_checkbox_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_email = pgTable(
  'forms_blocks_email',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_email_order_idx').on(columns._order),
    index('forms_blocks_email_parent_id_idx').on(columns._parentID),
    index('forms_blocks_email_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_email_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_number = pgTable(
  'forms_blocks_number',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    description: jsonb('description'),
    min: numeric('min', { mode: 'number' }),
    max: numeric('max', { mode: 'number' }),
    defaultValue: numeric('default_value', { mode: 'number' }),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_number_order_idx').on(columns._order),
    index('forms_blocks_number_parent_id_idx').on(columns._parentID),
    index('forms_blocks_number_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_number_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select_options = pgTable(
  'forms_blocks_select_options',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('forms_blocks_select_options_order_idx').on(columns._order),
    index('forms_blocks_select_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms_blocks_select.id],
      name: 'forms_blocks_select_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_select = pgTable(
  'forms_blocks_select',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    description: jsonb('description'),
    placeholder: varchar('placeholder'),
    defaultValue: varchar('default_value'),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_select_order_idx').on(columns._order),
    index('forms_blocks_select_parent_id_idx').on(columns._parentID),
    index('forms_blocks_select_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_select_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_text = pgTable(
  'forms_blocks_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    description: jsonb('description'),
    placeholder: varchar('placeholder'),
    defaultValue: varchar('default_value'),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_text_order_idx').on(columns._order),
    index('forms_blocks_text_parent_id_idx').on(columns._parentID),
    index('forms_blocks_text_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms_blocks_textarea = pgTable(
  'forms_blocks_textarea',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    label: varchar('label'),
    description: jsonb('description'),
    placeholder: varchar('placeholder'),
    defaultValue: varchar('default_value'),
    required: boolean('required'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('forms_blocks_textarea_order_idx').on(columns._order),
    index('forms_blocks_textarea_parent_id_idx').on(columns._parentID),
    index('forms_blocks_textarea_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [forms.id],
      name: 'forms_blocks_textarea_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const forms = pgTable(
  'forms',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('forms_updated_at_idx').on(columns.updatedAt),
    index('forms_created_at_idx').on(columns.createdAt),
  ],
)

export const form_submissions = pgTable(
  'form_submissions',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    form: integer('form_id')
      .notNull()
      .references(() => forms.id, {
        onDelete: 'set null',
      }),
    submissionData: jsonb('submission_data').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('form_submissions_user_idx').on(columns.user),
    index('form_submissions_form_idx').on(columns.form),
    index('form_submissions_updated_at_idx').on(columns.updatedAt),
    index('form_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const novu_channels = pgTable(
  'novu_channels',
  {
    id: serial('id').primaryKey(),
    subscriberId: varchar('subscriber_id').notNull(),
    hash: varchar('hash').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('novu_channels_updated_at_idx').on(columns.updatedAt),
    index('novu_channels_created_at_idx').on(columns.createdAt),
  ],
)

export const suppliers = pgTable(
  'suppliers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    status: enum_suppliers_status('status').notNull().default('ACTIVE'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('suppliers_updated_at_idx').on(columns.updatedAt),
    index('suppliers_created_at_idx').on(columns.createdAt),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    slug: varchar('slug'),
    slugLock: boolean('slug_lock').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => [
    index('posts_image_idx').on(columns.image),
    index('posts_slug_idx').on(columns.slug),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
    index('posts__status_idx').on(columns._status),
  ],
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'post-tagsID': integer('post_tags_id'),
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_post_tags_id_idx').on(columns['post-tagsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['post-tagsID']],
      foreignColumns: [post_tags.id],
      name: 'posts_rels_post_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_image: integer('version_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_excerpt: varchar('version_excerpt'),
    version_content: jsonb('version_content'),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_slug: varchar('version_slug'),
    version_slugLock: boolean('version_slug_lock').default(true),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_posts_v_parent_idx').on(columns.parent),
    index('_posts_v_version_version_image_idx').on(columns.version_image),
    index('_posts_v_version_version_slug_idx').on(columns.version_slug),
    index('_posts_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_posts_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_posts_v_version_version__status_idx').on(columns.version__status),
    index('_posts_v_created_at_idx').on(columns.createdAt),
    index('_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_posts_v_latest_idx').on(columns.latest),
    index('_posts_v_autosave_idx').on(columns.autosave),
  ],
)

export const _posts_v_rels = pgTable(
  '_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'post-tagsID': integer('post_tags_id'),
  },
  (columns) => [
    index('_posts_v_rels_order_idx').on(columns.order),
    index('_posts_v_rels_parent_idx').on(columns.parent),
    index('_posts_v_rels_path_idx').on(columns.path),
    index('_posts_v_rels_post_tags_id_idx').on(columns['post-tagsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['post-tagsID']],
      foreignColumns: [post_tags.id],
      name: '_posts_v_rels_post_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const post_tags = pgTable(
  'post_tags',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    slugLock: boolean('slug_lock').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('post_tags_slug_idx').on(columns.slug),
    index('post_tags_updated_at_idx').on(columns.updatedAt),
    index('post_tags_created_at_idx').on(columns.createdAt),
  ],
)

export const vouchers = pgTable(
  'vouchers',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    discountType: enum_vouchers_discount_type('discount_type').notNull(),
    discountValue: numeric('discount_value', { mode: 'number' }).notNull(),
    minPurchase: numeric('min_purchase', { mode: 'number' }),
    maxUses: numeric('max_uses', { mode: 'number' }),
    usedCount: numeric('used_count', { mode: 'number' }).default(0),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    expirationDate: timestamp('expiration_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    active: boolean('active').default(true),
    affiliateUser: integer('affiliate_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    commissionType: enum_vouchers_commission_type('commission_type'),
    commissionValue: numeric('commission_value', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('vouchers_code_idx').on(columns.code),
    index('vouchers_affiliate_user_idx').on(columns.affiliateUser),
    index('vouchers_updated_at_idx').on(columns.updatedAt),
    index('vouchers_created_at_idx').on(columns.createdAt),
  ],
)

export const vouchers_rels = pgTable(
  'vouchers_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
    'product-variantsID': integer('product_variants_id'),
  },
  (columns) => [
    index('vouchers_rels_order_idx').on(columns.order),
    index('vouchers_rels_parent_idx').on(columns.parent),
    index('vouchers_rels_path_idx').on(columns.path),
    index('vouchers_rels_products_id_idx').on(columns.productsID),
    index('vouchers_rels_product_variants_id_idx').on(columns['product-variantsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [vouchers.id],
      name: 'vouchers_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'vouchers_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['product-variantsID']],
      foreignColumns: [product_variants.id],
      name: 'vouchers_rels_product_variants_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
    categoriesID: integer('categories_id'),
    'category-groupsID': integer('category_groups_id'),
    accountsID: integer('accounts_id'),
    usersID: integer('users_id'),
    stocksID: integer('stocks_id'),
    transactionsID: integer('transactions_id'),
    productsID: integer('products_id'),
    'product-variantsID': integer('product_variants_id'),
    'product-variant-suppliesID': integer('product_variant_supplies_id'),
    ordersID: integer('orders_id'),
    rechargesID: integer('recharges_id'),
    formsID: integer('forms_id'),
    'form-submissionsID': integer('form_submissions_id'),
    'novu-channelsID': integer('novu_channels_id'),
    suppliersID: integer('suppliers_id'),
    postsID: integer('posts_id'),
    'post-tagsID': integer('post_tags_id'),
    vouchersID: integer('vouchers_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_category_groups_id_idx').on(columns['category-groupsID']),
    index('payload_locked_documents_rels_accounts_id_idx').on(columns.accountsID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_stocks_id_idx').on(columns.stocksID),
    index('payload_locked_documents_rels_transactions_id_idx').on(columns.transactionsID),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_product_variants_id_idx').on(
      columns['product-variantsID'],
    ),
    index('payload_locked_documents_rels_product_variant_supplies_i_idx').on(
      columns['product-variant-suppliesID'],
    ),
    index('payload_locked_documents_rels_orders_id_idx').on(columns.ordersID),
    index('payload_locked_documents_rels_recharges_id_idx').on(columns.rechargesID),
    index('payload_locked_documents_rels_forms_id_idx').on(columns.formsID),
    index('payload_locked_documents_rels_form_submissions_id_idx').on(
      columns['form-submissionsID'],
    ),
    index('payload_locked_documents_rels_novu_channels_id_idx').on(columns['novu-channelsID']),
    index('payload_locked_documents_rels_suppliers_id_idx').on(columns.suppliersID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_post_tags_id_idx').on(columns['post-tagsID']),
    index('payload_locked_documents_rels_vouchers_id_idx').on(columns.vouchersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['category-groupsID']],
      foreignColumns: [category_groups.id],
      name: 'payload_locked_documents_rels_category_groups_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['accountsID']],
      foreignColumns: [accounts.id],
      name: 'payload_locked_documents_rels_accounts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['stocksID']],
      foreignColumns: [stocks.id],
      name: 'payload_locked_documents_rels_stocks_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transactionsID']],
      foreignColumns: [transactions.id],
      name: 'payload_locked_documents_rels_transactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['product-variantsID']],
      foreignColumns: [product_variants.id],
      name: 'payload_locked_documents_rels_product_variants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['product-variant-suppliesID']],
      foreignColumns: [product_variant_supplies.id],
      name: 'payload_locked_documents_rels_product_variant_supplies_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['ordersID']],
      foreignColumns: [orders.id],
      name: 'payload_locked_documents_rels_orders_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['rechargesID']],
      foreignColumns: [recharges.id],
      name: 'payload_locked_documents_rels_recharges_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['formsID']],
      foreignColumns: [forms.id],
      name: 'payload_locked_documents_rels_forms_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['form-submissionsID']],
      foreignColumns: [form_submissions.id],
      name: 'payload_locked_documents_rels_form_submissions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['novu-channelsID']],
      foreignColumns: [novu_channels.id],
      name: 'payload_locked_documents_rels_novu_channels_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['suppliersID']],
      foreignColumns: [suppliers.id],
      name: 'payload_locked_documents_rels_suppliers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['post-tagsID']],
      foreignColumns: [post_tags.id],
      name: 'payload_locked_documents_rels_post_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['vouchersID']],
      foreignColumns: [vouchers.id],
      name: 'payload_locked_documents_rels_vouchers_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const header = pgTable('header', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const footer = pgTable('footer', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_media = relations(media, () => ({}))
export const relations_categories = relations(categories, () => ({}))
export const relations_category_groups_rels = relations(category_groups_rels, ({ one }) => ({
  parent: one(category_groups, {
    fields: [category_groups_rels.parent],
    references: [category_groups.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [category_groups_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations_category_groups = relations(category_groups, ({ many }) => ({
  _rels: many(category_groups_rels, {
    relationName: '_rels',
  }),
}))
export const relations_accounts = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: 'roles',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: 'roles',
  }),
}))
export const relations_stocks = relations(stocks, ({ one }) => ({
  order: one(orders, {
    fields: [stocks.order],
    references: [orders.id],
    relationName: 'order',
  }),
  productVariant: one(product_variants, {
    fields: [stocks.productVariant],
    references: [product_variants.id],
    relationName: 'productVariant',
  }),
}))
export const relations_transactions = relations(transactions, ({ one }) => ({
  user: one(users, {
    fields: [transactions.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  'product-variantsID': one(product_variants, {
    fields: [products_rels['product-variantsID']],
    references: [product_variants.id],
    relationName: 'product-variants',
  }),
  productsID: one(products, {
    fields: [products_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  image: one(media, {
    fields: [products.image],
    references: [media.id],
    relationName: 'image',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations_product_variants = relations(product_variants, ({ one }) => ({
  product: one(products, {
    fields: [product_variants.product],
    references: [products.id],
    relationName: 'product',
  }),
  image: one(media, {
    fields: [product_variants.image],
    references: [media.id],
    relationName: 'image',
  }),
  form: one(forms, {
    fields: [product_variants.form],
    references: [forms.id],
    relationName: 'form',
  }),
  defaultSupplier: one(suppliers, {
    fields: [product_variants.defaultSupplier],
    references: [suppliers.id],
    relationName: 'defaultSupplier',
  }),
}))
export const relations_product_variant_supplies = relations(
  product_variant_supplies,
  ({ one }) => ({
    productVariant: one(product_variants, {
      fields: [product_variant_supplies.productVariant],
      references: [product_variants.id],
      relationName: 'productVariant',
    }),
    supplier: one(suppliers, {
      fields: [product_variant_supplies.supplier],
      references: [suppliers.id],
      relationName: 'supplier',
    }),
  }),
)
export const relations_orders_rels = relations(orders_rels, ({ one }) => ({
  parent: one(orders, {
    fields: [orders_rels.parent],
    references: [orders.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [orders_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_orders = relations(orders, ({ one, many }) => ({
  orderedBy: one(users, {
    fields: [orders.orderedBy],
    references: [users.id],
    relationName: 'orderedBy',
  }),
  productVariant: one(product_variants, {
    fields: [orders.productVariant],
    references: [product_variants.id],
    relationName: 'productVariant',
  }),
  formSubmission: one(form_submissions, {
    fields: [orders.formSubmission],
    references: [form_submissions.id],
    relationName: 'formSubmission',
  }),
  supplier: one(suppliers, {
    fields: [orders.supplier],
    references: [suppliers.id],
    relationName: 'supplier',
  }),
  voucher: one(vouchers, {
    fields: [orders.voucher],
    references: [vouchers.id],
    relationName: 'voucher',
  }),
  affiliateUser: one(users, {
    fields: [orders.affiliateUser],
    references: [users.id],
    relationName: 'affiliateUser',
  }),
  _rels: many(orders_rels, {
    relationName: '_rels',
  }),
}))
export const relations_recharges = relations(recharges, ({ one }) => ({
  user: one(users, {
    fields: [recharges.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_forms_blocks_checkbox = relations(forms_blocks_checkbox, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_checkbox._parentID],
    references: [forms.id],
    relationName: '_blocks_checkbox',
  }),
}))
export const relations_forms_blocks_email = relations(forms_blocks_email, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_email._parentID],
    references: [forms.id],
    relationName: '_blocks_email',
  }),
}))
export const relations_forms_blocks_number = relations(forms_blocks_number, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_number._parentID],
    references: [forms.id],
    relationName: '_blocks_number',
  }),
}))
export const relations_forms_blocks_select_options = relations(
  forms_blocks_select_options,
  ({ one }) => ({
    _parentID: one(forms_blocks_select, {
      fields: [forms_blocks_select_options._parentID],
      references: [forms_blocks_select.id],
      relationName: 'options',
    }),
  }),
)
export const relations_forms_blocks_select = relations(forms_blocks_select, ({ one, many }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_select._parentID],
    references: [forms.id],
    relationName: '_blocks_select',
  }),
  options: many(forms_blocks_select_options, {
    relationName: 'options',
  }),
}))
export const relations_forms_blocks_text = relations(forms_blocks_text, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_text._parentID],
    references: [forms.id],
    relationName: '_blocks_text',
  }),
}))
export const relations_forms_blocks_textarea = relations(forms_blocks_textarea, ({ one }) => ({
  _parentID: one(forms, {
    fields: [forms_blocks_textarea._parentID],
    references: [forms.id],
    relationName: '_blocks_textarea',
  }),
}))
export const relations_forms = relations(forms, ({ many }) => ({
  _blocks_checkbox: many(forms_blocks_checkbox, {
    relationName: '_blocks_checkbox',
  }),
  _blocks_email: many(forms_blocks_email, {
    relationName: '_blocks_email',
  }),
  _blocks_number: many(forms_blocks_number, {
    relationName: '_blocks_number',
  }),
  _blocks_select: many(forms_blocks_select, {
    relationName: '_blocks_select',
  }),
  _blocks_text: many(forms_blocks_text, {
    relationName: '_blocks_text',
  }),
  _blocks_textarea: many(forms_blocks_textarea, {
    relationName: '_blocks_textarea',
  }),
}))
export const relations_form_submissions = relations(form_submissions, ({ one }) => ({
  user: one(users, {
    fields: [form_submissions.user],
    references: [users.id],
    relationName: 'user',
  }),
  form: one(forms, {
    fields: [form_submissions.form],
    references: [forms.id],
    relationName: 'form',
  }),
}))
export const relations_novu_channels = relations(novu_channels, () => ({}))
export const relations_suppliers = relations(suppliers, () => ({}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  'post-tagsID': one(post_tags, {
    fields: [posts_rels['post-tagsID']],
    references: [post_tags.id],
    relationName: 'post-tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  image: one(media, {
    fields: [posts.image],
    references: [media.id],
    relationName: 'image',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: '_rels',
  }),
  'post-tagsID': one(post_tags, {
    fields: [_posts_v_rels['post-tagsID']],
    references: [post_tags.id],
    relationName: 'post-tags',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_image: one(media, {
    fields: [_posts_v.version_image],
    references: [media.id],
    relationName: 'version_image',
  }),
  _rels: many(_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_post_tags = relations(post_tags, () => ({}))
export const relations_vouchers_rels = relations(vouchers_rels, ({ one }) => ({
  parent: one(vouchers, {
    fields: [vouchers_rels.parent],
    references: [vouchers.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [vouchers_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
  'product-variantsID': one(product_variants, {
    fields: [vouchers_rels['product-variantsID']],
    references: [product_variants.id],
    relationName: 'product-variants',
  }),
}))
export const relations_vouchers = relations(vouchers, ({ one, many }) => ({
  affiliateUser: one(users, {
    fields: [vouchers.affiliateUser],
    references: [users.id],
    relationName: 'affiliateUser',
  }),
  _rels: many(vouchers_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    'category-groupsID': one(category_groups, {
      fields: [payload_locked_documents_rels['category-groupsID']],
      references: [category_groups.id],
      relationName: 'category-groups',
    }),
    accountsID: one(accounts, {
      fields: [payload_locked_documents_rels.accountsID],
      references: [accounts.id],
      relationName: 'accounts',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    stocksID: one(stocks, {
      fields: [payload_locked_documents_rels.stocksID],
      references: [stocks.id],
      relationName: 'stocks',
    }),
    transactionsID: one(transactions, {
      fields: [payload_locked_documents_rels.transactionsID],
      references: [transactions.id],
      relationName: 'transactions',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    'product-variantsID': one(product_variants, {
      fields: [payload_locked_documents_rels['product-variantsID']],
      references: [product_variants.id],
      relationName: 'product-variants',
    }),
    'product-variant-suppliesID': one(product_variant_supplies, {
      fields: [payload_locked_documents_rels['product-variant-suppliesID']],
      references: [product_variant_supplies.id],
      relationName: 'product-variant-supplies',
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: 'orders',
    }),
    rechargesID: one(recharges, {
      fields: [payload_locked_documents_rels.rechargesID],
      references: [recharges.id],
      relationName: 'recharges',
    }),
    formsID: one(forms, {
      fields: [payload_locked_documents_rels.formsID],
      references: [forms.id],
      relationName: 'forms',
    }),
    'form-submissionsID': one(form_submissions, {
      fields: [payload_locked_documents_rels['form-submissionsID']],
      references: [form_submissions.id],
      relationName: 'form-submissions',
    }),
    'novu-channelsID': one(novu_channels, {
      fields: [payload_locked_documents_rels['novu-channelsID']],
      references: [novu_channels.id],
      relationName: 'novu-channels',
    }),
    suppliersID: one(suppliers, {
      fields: [payload_locked_documents_rels.suppliersID],
      references: [suppliers.id],
      relationName: 'suppliers',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    'post-tagsID': one(post_tags, {
      fields: [payload_locked_documents_rels['post-tagsID']],
      references: [post_tags.id],
      relationName: 'post-tags',
    }),
    vouchersID: one(vouchers, {
      fields: [payload_locked_documents_rels.vouchersID],
      references: [vouchers.id],
      relationName: 'vouchers',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_header = relations(header, () => ({}))
export const relations_footer = relations(footer, () => ({}))

type DatabaseSchema = {
  enum_category_groups_sort_products: typeof enum_category_groups_sort_products
  enum_users_roles: typeof enum_users_roles
  enum_products_status: typeof enum_products_status
  enum_product_variants_status: typeof enum_product_variants_status
  enum_product_variants_auto_process: typeof enum_product_variants_auto_process
  enum_orders_status: typeof enum_orders_status
  enum_recharges_status: typeof enum_recharges_status
  enum_recharges_gateway: typeof enum_recharges_gateway
  enum_suppliers_status: typeof enum_suppliers_status
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum_vouchers_discount_type: typeof enum_vouchers_discount_type
  enum_vouchers_commission_type: typeof enum_vouchers_commission_type
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  media: typeof media
  categories: typeof categories
  category_groups: typeof category_groups
  category_groups_rels: typeof category_groups_rels
  accounts: typeof accounts
  users_roles: typeof users_roles
  users: typeof users
  stocks: typeof stocks
  transactions: typeof transactions
  products: typeof products
  products_rels: typeof products_rels
  product_variants: typeof product_variants
  product_variant_supplies: typeof product_variant_supplies
  orders: typeof orders
  orders_rels: typeof orders_rels
  recharges: typeof recharges
  forms_blocks_checkbox: typeof forms_blocks_checkbox
  forms_blocks_email: typeof forms_blocks_email
  forms_blocks_number: typeof forms_blocks_number
  forms_blocks_select_options: typeof forms_blocks_select_options
  forms_blocks_select: typeof forms_blocks_select
  forms_blocks_text: typeof forms_blocks_text
  forms_blocks_textarea: typeof forms_blocks_textarea
  forms: typeof forms
  form_submissions: typeof form_submissions
  novu_channels: typeof novu_channels
  suppliers: typeof suppliers
  posts: typeof posts
  posts_rels: typeof posts_rels
  _posts_v: typeof _posts_v
  _posts_v_rels: typeof _posts_v_rels
  post_tags: typeof post_tags
  vouchers: typeof vouchers
  vouchers_rels: typeof vouchers_rels
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  header: typeof header
  footer: typeof footer
  relations_media: typeof relations_media
  relations_categories: typeof relations_categories
  relations_category_groups_rels: typeof relations_category_groups_rels
  relations_category_groups: typeof relations_category_groups
  relations_accounts: typeof relations_accounts
  relations_users_roles: typeof relations_users_roles
  relations_users: typeof relations_users
  relations_stocks: typeof relations_stocks
  relations_transactions: typeof relations_transactions
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations_product_variants: typeof relations_product_variants
  relations_product_variant_supplies: typeof relations_product_variant_supplies
  relations_orders_rels: typeof relations_orders_rels
  relations_orders: typeof relations_orders
  relations_recharges: typeof relations_recharges
  relations_forms_blocks_checkbox: typeof relations_forms_blocks_checkbox
  relations_forms_blocks_email: typeof relations_forms_blocks_email
  relations_forms_blocks_number: typeof relations_forms_blocks_number
  relations_forms_blocks_select_options: typeof relations_forms_blocks_select_options
  relations_forms_blocks_select: typeof relations_forms_blocks_select
  relations_forms_blocks_text: typeof relations_forms_blocks_text
  relations_forms_blocks_textarea: typeof relations_forms_blocks_textarea
  relations_forms: typeof relations_forms
  relations_form_submissions: typeof relations_form_submissions
  relations_novu_channels: typeof relations_novu_channels
  relations_suppliers: typeof relations_suppliers
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations__posts_v_rels: typeof relations__posts_v_rels
  relations__posts_v: typeof relations__posts_v
  relations_post_tags: typeof relations_post_tags
  relations_vouchers_rels: typeof relations_vouchers_rels
  relations_vouchers: typeof relations_vouchers
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_header: typeof relations_header
  relations_footer: typeof relations_footer
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
